---
title: "HOMEWORK 3"
output: html_notebook
author: Diana Gutierrez 999012382
---

```{r}
library(gapminder)
library(dplyr)
```

#PRIMERA PARTE 
```{r}
dataset_results <- read.csv("primary_results.csv")
dataset_results
```

```{r}
dataset_results %>%
  filter(state == "Florida")
```
#SEGUNDA PARTE
```{r}
dataset_results %>% 
  filter(candidate == "Donald Trump" | candidate == "Hillary Clinton")

```

```{r}
dataset_results %>%
  filter(party == "Democrat" & county == "Shelby")
```
```{r}
dataset_results %>%
  filter(state == "Alabama" & votes > 15000)
```
#TERCERA PARTE
```{r}
dataset_results %>%
  filter(state == "Texas" & county == "Denton") %>%
  select(5:7) %>%
  arrange(desc(votes))
```
#CUARTA PARTE
Filtrar por el partido Republicano, que el candidato sea Ted Cruz en el estado de
Alaska, luego agregue una columna que se llame vote_count que sea la división de
votes por fraction_votes (votes/fraction_votes), finalmente ordene de forma
descendente por vote_count.

```{r}
dataset_results %>%
  filter(party == "Republican" & candidate == "Ted Cruz" & state == "Alaska")
  mutate(dataset_results, vote_count = votes/fraction_votes) %>%
  arrange(desc(vote_count))

```




