---
title: "Homework 4"
output: html_notebook
author: Diana Gutierrez
---

```{r}
diamonds <- read.csv("diamonds.csv")
diamonds
```

```{r}
library(tidyverse)
library(dplyr)
library(lubridate)
```
```{r}
str(diamonds)
```
1. Dispersión
1.1
```{r}
ggplot(diamonds, aes(x=carat, y=price)) + geom_point()
```
1.2,1.3
```{r}
ggplot(diamonds, aes(x=carat, y=price, color= clarity)) + geom_point() + labs(x= "Quilates", y= "Precio", color= "Claridad")
```
Histograma
2.1
```{r}
ggplot(diamonds, aes(price)) + geom_histogram(bins=40) + labs(x="Precio", y= "Conteo")
```
2.2 Escala logarítmica
```{r}
ggplot(diamonds, aes(price)) + geom_histogram(bins=40) + scale_x_log10()+scale_y_log10() + labs(x="Precio", y= "Conteo")
```
3. Boxplots
3.1
```{r}
ggplot(diamonds, aes(x=cut, y= price)) + scale_y_log10() + geom_boxplot()+ labs(x= "Corte", y ="Precio")
```
3.2
```{r}
ggplot(diamonds, aes(x=cut, y= price, fill=cut)) + scale_y_log10() + geom_boxplot()+ labs(x= "Corte", y ="Precio", fill="Corte")
```
4. Faceting
4.1
```{r}
filtered_price <-filter(diamonds, price > 1000 & cut%in%c("Good", "Ideal", "Premium") )

filtered_price
```
4.2
```{r}
ggplot(filtered_price, aes(depth)) + geom_bar() + labs(x="Corte", y="Profundidad")
```
4.3 
```{r}
ggplot(filtered_price, aes(depth)) + geom_bar() + labs(x="Corte", y="Profundidad")+
  facet_wrap(~clarity)
```
```{r}
ggplot(filtered_price, aes(depth, fill=clarity)) + geom_bar() + labs(x="Corte", y="Profundidad", fill= "Claridad")+
  facet_wrap(~clarity)
```
Grouping and summarizing
1.
```{r}
median_dimension_diamond<-diamonds%>%
  group_by(cut)%>%
  summarize(mediaX = median(x),mediaY = median(y), mediaZ = median(z))
  
median_dimension_diamond
```
2. 
```{r}
cut_premium <-diamonds%>%
  filter(cut=="Premium")%>%
  group_by(clarity)%>%
  summarize(minPrice = min(price), maxPrice = max(price))

cut_premium

```
3. 
```{r}
ggplot(cut_premium, aes(maxPrice, fill=clarity)) + geom_bar() + labs(x="Claridad", y="Precio máximo", fill="Claridad")
```


